/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJApplet.java
 *
 * Created on 27.05.2012, 14:23:38
 */
package gui;

/**
 *
 * @author Doro
 */
public class NewJApplet extends javax.swing.JApplet {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel pLossLb;
    private javax.swing.JTextField pLossTF;
    private javax.swing.JLabel pNameLb;
    private javax.swing.JTextField pNameTF;
    private javax.swing.JLabel pScoreLb;
    private javax.swing.JTextField pScoreTF;
    private javax.swing.JLabel pWinsLb;
    private javax.swing.JTextField pWinsTF;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JRadioButton qAntwort1;
    private javax.swing.JRadioButton qAntwort2;
    private javax.swing.JRadioButton qAntwort3;
    private javax.swing.JRadioButton qAntwort4;
    private javax.swing.JLabel qBild;
    private javax.swing.JLabel qLossLb;
    private javax.swing.JTextField qLossTF;
    private javax.swing.JTextField qNr;
    private javax.swing.JLabel qNrLb;
    private javax.swing.JLabel qScoreLb;
    private javax.swing.JTextField qScoreTF;
    private javax.swing.JLabel qWinsLb;
    private javax.swing.JTextField qWinsTF;
    private javax.swing.JPanel quizFragePanel;
    private javax.swing.JPanel quizStats;
    private javax.swing.JButton stopBtn;
    private javax.swing.JTextField timer;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    /** Initializes the applet NewJApplet */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * 
     * @param args 
     */
    public static void main(String[] args) {
        NewJApplet mvqApplet = new NewJApplet();

    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        playerPanel = new javax.swing.JPanel();
        pWinsLb = new javax.swing.JLabel();
        pLossLb = new javax.swing.JLabel();
        pScoreLb = new javax.swing.JLabel();
        pNameTF = new javax.swing.JTextField();
        pWinsTF = new javax.swing.JTextField();
        pLossTF = new javax.swing.JTextField();
        pScoreTF = new javax.swing.JTextField();
        pNameLb = new javax.swing.JLabel();
        quizFragePanel = new javax.swing.JPanel();
        qBild = new javax.swing.JLabel();
        qAntwort1 = new javax.swing.JRadioButton();
        qAntwort2 = new javax.swing.JRadioButton();
        qAntwort3 = new javax.swing.JRadioButton();
        qAntwort4 = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        timer = new javax.swing.JTextField();
        qNrLb = new javax.swing.JLabel();
        qNr = new javax.swing.JTextField();
        quizStats = new javax.swing.JPanel();
        qWinsLb = new javax.swing.JLabel();
        qLossLb = new javax.swing.JLabel();
        qScoreLb = new javax.swing.JLabel();
        qWinsTF = new javax.swing.JTextField();
        qLossTF = new javax.swing.JTextField();
        qScoreTF = new javax.swing.JTextField();

        playerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        playerPanel.setName(""); // NOI18N

        pWinsLb.setText("Gewonnen:");

        pLossLb.setText("Verloren:");

        pScoreLb.setText("Gesamt-Score:");

        pNameTF.setEditable(false);
        pNameTF.setText("jTextField1");

        pWinsTF.setEditable(false);
        pWinsTF.setText("jTextField2");

        pLossTF.setEditable(false);
        pLossTF.setText("jTextField3");

        pScoreTF.setEditable(false);
        pScoreTF.setText("jTextField4");

        pNameLb.setText("Name:");

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pNameLb)
                .addGap(15, 15, 15)
                .addComponent(pNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pScoreLb)
                    .addComponent(pWinsLb)
                    .addComponent(pLossLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pScoreTF, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(pLossTF)
                    .addComponent(pWinsTF))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pWinsLb)
                    .addComponent(pWinsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNameLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pLossLb)
                    .addComponent(pLossTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pScoreLb)
                    .addComponent(pScoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        quizFragePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        qBild.setText("jLabel6");
        qBild.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, qBild, org.jdesktop.beansbinding.ObjectProperty.create(), qBild, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        qAntwort1.setText("jRadioButton1");

        qAntwort2.setText("jRadioButton2");

        qAntwort3.setText("jRadioButton3");

        qAntwort4.setText("jRadioButton4");

        nextBtn.setText("Passe");
        nextBtn.setToolTipText("nächster Film");

        stopBtn.setText("Gebe auf");

        timer.setEditable(false);
        timer.setText("timer");
        timer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerActionPerformed(evt);
            }
        });

        qNrLb.setText("Quiz-Nr.:");

        qNr.setEditable(false);
        qNr.setText("jTextField1");

        javax.swing.GroupLayout quizFragePanelLayout = new javax.swing.GroupLayout(quizFragePanel);
        quizFragePanel.setLayout(quizFragePanelLayout);
        quizFragePanelLayout.setHorizontalGroup(
            quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFragePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizFragePanelLayout.createSequentialGroup()
                        .addComponent(qBild, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizFragePanelLayout.createSequentialGroup()
                                .addComponent(stopBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(nextBtn))
                            .addComponent(qAntwort3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(qAntwort2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(qAntwort1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(qAntwort4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(quizFragePanelLayout.createSequentialGroup()
                        .addComponent(qNrLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        quizFragePanelLayout.setVerticalGroup(
            quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFragePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qNrLb)
                    .addComponent(qNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizFragePanelLayout.createSequentialGroup()
                        .addComponent(qAntwort1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qAntwort2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qAntwort3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qAntwort4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(quizFragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextBtn)
                            .addComponent(stopBtn)))
                    .addComponent(qBild, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );

        quizStats.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        qWinsLb.setText("Gewonnen:");

        qLossLb.setText("Verloren:");

        qScoreLb.setText("Score:");

        qWinsTF.setEditable(false);
        qWinsTF.setText("jTextField1");

        qLossTF.setEditable(false);
        qLossTF.setText("jTextField2");

        qScoreTF.setEditable(false);
        qScoreTF.setText("jTextField3");

        javax.swing.GroupLayout quizStatsLayout = new javax.swing.GroupLayout(quizStats);
        quizStats.setLayout(quizStatsLayout);
        quizStatsLayout.setHorizontalGroup(
            quizStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qWinsLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qWinsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(qLossLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qLossTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(qScoreLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qScoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        quizStatsLayout.setVerticalGroup(
            quizStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qWinsLb)
                    .addComponent(qLossLb)
                    .addComponent(qScoreLb)
                    .addComponent(qWinsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qLossTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qScoreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quizStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizFragePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizFragePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        playerPanel.getAccessibleContext().setAccessibleName("null");

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void timerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_timerActionPerformed
    }
    
    
}
